[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_marketplace = "4HCZ6cN38fX1odvW43ckBawdDWAEffrXvKoC2gemLSoT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/es/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
